fix: crash on Android hot reloading (#130)
## 📜 Description

Fixed a crash on Android when performing a hot reload.

## 💡 Motivation and Context

When we reload the app we restart the Activity. Before we didn't clean
up the attached children and we were trying to attach them twice
afterwards which was leading to crash:

```bash
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
  at android.view.ViewGroup.addViewInner(ViewGroup.java:5286)
  at android.view.ViewGroup.addView(ViewGroup.java:5115)
  at android.view.ViewGroup.addView(ViewGroup.java:5055)
```

In this PR I fixed that - I detect a moment when view is getting
destroyed and clean up all internal resources. In this way we avoid the
crash 🤞

Closes https://github.com/kirillzyusko/react-native-teleport/issues/129

## 📢 Changelog

<!-- High level overview of important changes -->
<!-- For example: fixed status bar manipulation; added new types
declarations; -->
<!-- If your changes don't affect one of platform/language below - then
remove this platform/language -->

### Android

- added `cleanup` to `PortalView`;
- call `cleanup` in `PortalViewManager` on `onDropViewInstance`;

## 🤔 How Has This Been Tested?

Tested manually on Pixel 8 (API 36).

## 📸 Screenshots (if appropriate):

|Before|After|
|-------|-----|
|<video
src="https://github.com/user-attachments/assets/6373388f-cdcb-4f9d-890d-832071660b57">|<video
src="https://github.com/user-attachments/assets/7b2efed1-7dc9-4104-8eb0-3f0f4595d826">|

## 📝 Checklist

- [x] CI successfully passed
- [x] I added new mocks and corresponding unit-tests if library API was
changed