fix: a11y crash on Android (#7)
## 📜 Description

Fixed a11y crash when focusing teleported element.

## 💡 Motivation and Context

When we teleport `children` to a different host using
`PortalRegistry.getHost(hostName)?.addView(child)`, the `children` are
physically moved to the host's view hierarchy. However, overridden
`getChildCount()` and `getChildAt()` methods in `PortalView` return the
`children` from the host when teleported. This confuses the
accessibility system because it expects these children to be direct
descendants of `PortalView` for coordinate calculation, but they are
not.

We need to ensure that the `PortalView` does not expose teleported
children to the accessibility system. For that we override
`addChildrenForAccessibility()` in `PortalView` to exclude teleported
children when they are not in the local hierarchy and it fixes the
crash:

```bash
2025-09-09 11:29:39.808 30050-30050 AndroidRuntime          teleport.example                     E  FATAL EXCEPTION: main
                                                                                                    Process: teleport.example, PID: 30050
                                                                                                    java.lang.IllegalArgumentException: parameter must be a descendant of this view
                                                                                                    	at android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:6295)
                                                                                                    	at android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:6224)
                                                                                                    	at android.view.ViewGroup$ViewLocationHolder.init(ViewGroup.java:9189)
                                                                                                    	at android.view.ViewGroup$ViewLocationHolder.obtain(ViewGroup.java:9070)
                                                                                                    	at android.view.ViewGroup$ChildListForAccessibility.init(ViewGroup.java:9003)
                                                                                                    	at android.view.ViewGroup$ChildListForAccessibility.obtain(ViewGroup.java:8975)
                                                                                                    	at android.view.ViewGroup.addChildrenForAccessibility(ViewGroup.java:2455)
                                                                                                    	at com.facebook.react.views.view.ReactViewGroup.addChildrenForAccessibility(ReactViewGroup.kt:994)
                                                                                                    	at android.view.ViewGroup.onInitializeAccessibilityNodeInfoInternal(ViewGroup.java:3798)
                                                                                                    	at android.view.View.onInitializeAccessibilityNodeInfo(View.java:8613)
                                                                                                    	at android.view.View.createAccessibilityNodeInfoInternal(View.java:8572)
                                                                                                    	at android.view.View.createAccessibilityNodeInfo(View.java:8557)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1358)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1381)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1381)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1381)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1381)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1381)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1381)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1381)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1381)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1381)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1381)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1381)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1381)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1381)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1381)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1381)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:1183)
                                                                                                    	at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:368)
                                                                                                    	at android.view.AccessibilityInteractionController.access$500(AccessibilityInteractionController.java:74)
2025-09-09 11:29:39.809 30050-30050 AndroidRuntime          teleport.example                     E  	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1547)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2025-09-09 11:29:39.825 30050-30050 Process                 teleport.example                     I  Sending signal. PID: 30050 SIG: 9
```

## 📢 Changelog

<!-- High level overview of important changes -->
<!-- For example: fixed status bar manipulation; added new types
declarations; -->
<!-- If your changes don't affect one of platform/language below - then
remove this platform/language -->

### Android

- override `addChildrenForAccessibility` to handle a11y correctly;

## 🤔 How Has This Been Tested?

Tested manually via maestro tests (it uses a11y to send events).

## 📸 Screenshots (if appropriate):


https://github.com/user-attachments/assets/c47822f8-8d24-4917-8e45-c0a3e0e50348

## 📝 Checklist

- [x] CI successfully passed
- [x] I added new mocks and corresponding unit-tests if library API was
changed